### PR TITLE
Add a verbose parameter to disable the warning messages in the console

### LINKED ISSUE #37: Warning: Function copy already exists on CSM, renaming to base_copy
image

I have often this warning in the console, I wonder if there is a way to disable it? 

If not, would you agree to add a `verbose` property that we can set to false that would disable any warning in the console ?

For instance: 

```jsx
<CustomShaderMaterial
              baseMaterial={MeshPhongMaterial}
              uniforms={{}}
              verbose={false}
/>
```

Thank you in advance.

### PR DESCRIPTION
**Pull request by AxiomeCG**
I suggested a `verbose` parameter sometime ago, I had some time today, so I made it myself. 

I preserved the default behaviour of warning, so it is working as before. But we have now the possibility to disable the warnings, if it is polluting.

Resolves #37

### CODE REVIEW

**Comment by FarazzShaikh** [comment]
Thanks for the PR! I would like for this option to be true by default. So perhaps we can rename it it “silent” that if set will disable the messages 

this way we can avoid confusion from first time users who might interpret this behavior as s bug

We can also set it so that if in a production environment “silent” will be set by default

**Comment by AxiomeCG** [comment]
I thought I made sure that the boolean is set to true by default for verbose. 😀

Just to confirm with you, if we put silent, then making it false by default should be the way to go so the default behaviour is the same (showing the warnings by default and being able to silent them)

**Comment by FarazzShaikh** [comment]
Yes that is correct. Silent will false or undefined by default.

**Comment by AxiomeCG** [comment]
Roger that, I will make the update asap, thank you for the feedback !

**Comment by FarazzShaikh** [comment]
Of course! I appreciate the PR!

**Comment by AxiomeCG** [comment]
It should do the trick, I added a bit of documentation in the examples. Tell me if there is some of the things to change !

**Comment by FarazzShaikh** [comment]
Great thanks! I’m currently out on vacation, I will take a look at this as soon as I’m back in business.

**Review by FarazzShaikh — APPROVED** [review]

**Pull request merged**
